# Generated by Django 4.0.3 on 2022-04-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('contrasenia', models.TextField(max_length=20)),
            ],
        ),
    ]
