# Generated by Django 4.0.3 on 2022-04-28 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiNovatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=20)),
                ('direccion', models.TextField(max_length=20)),
                ('ciudad', models.TextField(max_length=20)),
                ('tel', models.TextField(max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField(max_length=20)),
                ('nombre', models.TextField(max_length=40)),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField(max_length=200)),
                ('ref_moto', models.TextField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_tarjeta', models.TextField(max_length=16)),
                ('cod_seguridad', models.TextField(max_length=3)),
                ('fecha_venc', models.TextField(max_length=5)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='medioPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.mediopago'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('opinion', models.TextField(max_length=200)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=200)),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.tienda')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.usuario')),
            ],
        ),
    ]
