# Generated by Django 4.0.4 on 2022-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNovatus', '0002_categoria_compra_usuario_direccion_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='marca_moto',
            field=models.TextField(default='Yamaha', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.TextField(default='cliente', max_length=10),
        ),
    ]
