# Generated by Django 4.0.4 on 2022-05-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiNovatus', '0004_remove_compra_id_cliente_remove_compra_mediopago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
    ]
