# Generated by Django 3.2 on 2022-05-24 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiNovatus', '0005_remove_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_cita',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiNovatus.tienda'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tienda',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
